build:
	g++ -O6 sublimelyMagnificentAlgorithmMarkII.cpp -o magicalMagikarp

command:
	@echo "./magicalMagikarp"

user:
	@echo "sipes"
	
sipesPlusUltra: sipesPlusUltra.c
	gcc -Ofast -fno-stack-protector -static -no-pie -o sipesPlusUltra sipesPlusUltra.c
