#!/bin/bash -
#Brandon Sipes
#April 17, 2018
#lab11 Wikipedia tool to lookup topics on wikipedia

######################################################
# Main
######################################################
function main(){
  lookup=$1
  shift
  for i in $*; do 
    lookup=${lookup}_$i
  done
  cURL=https://en.wikipedia.org/wiki/$lookup
  echo $cURL
  output=$(curl $cURL 2>/dev/null)
  smaller=${output%%<div id=\"toc*}
  final=${smaller#*<p>}
  echo $final | sed -r -e 's/<\/?p>/\n/g' -e 's/<[^>]*>//g'
}



main $*
