#!/bin/bash

#Brandon Sipes lab08 Creating a table of image thumbnails



# ====================================
# pagehead
# ====================================
#simple function to generate the head of the page
function pagehead () {
  cat<<EOF
<html>
  <head>
    <title>
      $1
    </title>
    <link rel="stylesheet" href="./calstyle.css">
  </head>
  <body>
    <h1>$1</h1>
    <table>
    <tr>
EOF
}

# ====================================
# pageend
# ====================================
#function to end each page
function pageend () {
  cat<<EOF
    </table>
  </body>
</html>
EOF
}



# ************************************
# readStdin
# ************************************
function readStdin () {
  while read fn; do
    if (( count == col )); then
      count=0
      cat<<END
      </tr>
      <tr>
END
    fi
    newFile=${fn%.*}.png
    convert $fn -resize '20%' $newFile
    echo "<td><a href=${fn}><img src=\"$newFile\"></a>"
    if (( useCap == 1 )); then
      read -r line < $capFile
      echo $line
    fi
    echo "</td>"
    let count++
  done >> $output
}

# ************************************
# usage
# ************************************
function usage () {
  cat<<ENOENT
Usage: ./mkablum [OPTION]... [FILES]...
Create an html table of image thumbnails

  -w           set the column number (default is 5)
  -t           set title of the table
  -c           accept a caption file
  -i           read from stdin
  -o           set output file name (default is album.html)
ENOENT
  exit
}



# ====================================
# main
# ====================================

col=5
title="image Table"
capFile="test.txt"
useCap=0
output="album.html"
input=0
kill=1
while getopts "w:t:c:io:" opt; do
  case $opt in
    w)col=$OPTARG;
      [ $OPTARG ];;
    t)title=$OPTARG;
      [ "$OPTARG" ];;
    c)capFile=$OPTARG;
      useCap=1;
      [ "$OPTARG" ];;
    i)input=1;;
    o)output=$OPTARG;
      [ "$OPTARG" ];;
    *)kill=0;;
  esac
done
if [ $kill -eq "0" ];then #something is wrong send usage message
  usage
  exit
fi

shift $((OPTIND-1)); #get right file path


pagehead "$title" > $output
count=0
echo "<tr>" >> $output
if [ $input -eq 1 ]; then
  readStdin
else
  for fn
  do
    if (( count == col )); then
      count=0
      cat<<END
      </tr>
      <tr>
END
    fi
    
    newFile=${fn%.*}.png
    convert $fn -resize '20%' $newFile
    echo "<td><a href=${fn}><img src=\"$newFile\" width=\"128\" height=\"128\"></a>"
    if (( useCap == 1 )); then
      read -r line < $capFile
      echo "<p>$line</p>"
    fi
    echo "</td>"
    let count++
  done >> $output
fi
echo "</tr>" >> $output
pageend >> $output

