build:	build-greedy #build-optval build-opt

build-greedy:
	g++ -O4 -o gog part1.cpp

comm-greedy:
	@echo "./gog"

#build-optval:
#	g++ -O4 -o gov solA.cpp

#comm-optval:
#	@echo "./gov"

#build-opt:
#	g++ -O4 -o goo solB.cpp

#comm-opt:
#	@echo "./goo"

#users:
#	@echo "bssipes"

clean:
	rm -f gog #gov goo rcheck
