#!/bin/bash -
#oodiff - diff the content of open office files
#Brandon Sipes April 10, 2018

##########################################################
# testFile - test the file extension
##########################################################
function testFile(){
  if [[ $1 != *.odt ]]; then 
    exit
  fi
}

##########################################################
# parseFiles
##########################################################
parseFiles (){
  sed 's/>/>\n/g' $1 | sed 's/<.*>//' | sed '/^$/d' > $1.txt
}


##########################################################
# main
##########################################################
function main(){
  Direct1=/tmp/oodiff1$RANDOM #hopefully unused directory
  Direct2=/tmp/oodiff2$RANDOM
  mkdir $Direct1
  mkdir $Direct2
  file1=$Direct1/oodiff #create two random files to store the unziped data
  file2=$Direct2/oodiff

  trap "rm -rf $Direct1 $Direct2" SIGINT SIGTERM SIGKILL EXIT SIGQUIT #trap as many things as might show up
  testFile $1 #test both file extensions
  testFile $2
  unzip -p $1 content.xml > $file1 #unzip the content.xml file out of each odt file
  unzip -p $2 content.xml > $file2
  
  parseFiles $file1 #Use sed to parse the files out
  parseFiles $file2
  diff -sby $file1.txt $file2.txt
}


main $*



